---
# Install any packeges for differetn OS
- name: Loops Playbook
  hosts: aws
  become: yes

  vars:
    pkg:
      - tree
      - htop
      - chrony

  tasks:
    - name: Insatall packages on Debian-like OS
      apt:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Insatall packages on RedHat-like OS
      yum:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Redhat"
